	<ul class="breadcrumb">
		<li class="dropdown">
		<a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#"><?php echo $this->category ?><b class="caret"></b></a>
			<ul id="branches-dropdown" class="dropdown-menu">
				<li><a tabindex="-1" href="catering">catering</a></li>
				<li><a tabindex="-1" href="construction">construction</a></li>
				<li><a tabindex="-1" href="travel">travel</a></li>
			</ul>
		</li>
		<li class="dropdown">
			<a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">ladder<b class="caret"></b></a>
			<ul id="branches-dropdown" class="dropdown-menu">
				<li><a tabindex="-1" href="ladder">ladder</a></li>
				<li><a tabindex="-1" href="fence">fence</a></li>
				<li><a tabindex="-1" href="portaloo">portaloo</a></li>
			</ul>
		</li>
	</ul>
