<div class="row">
<div class="col-xs-8" id="left">

  <h2><?php echo $this->category ?></h2>
  
  <!-- item list -->
  <?php echo $this->result_list ?>
  <!-- /item list -->
  
  <p>
  <a href="http://www.bootply.com/render/129229">Demo</a> | <a href="http://bootply.com/129229">Source Code</a>
  </p>
  
  <hr> 
	
  <p>
  <a href="http://bootply.com" target="_ext" class="center-block btn btn-primary">More Bootstrap Snippets on Bootply</a>
  </p>
	
  <hr>      

</div>
<?php echo $this->map ?>
</div>
