<div class="row">
<div class="col-xs-8" id="left">
	<ul class="breadcrumb">
		<li class="dropdown">
			<a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">construction <b class="caret"></b></a>
			<ul id="branches-dropdown" class="dropdown-menu">
				<li><a tabindex="-1" href="catering">catering</a></li>
				<li><a tabindex="-1" href="construction">construction</a></li>
				<li><a tabindex="-1" href="travel">travel</a></li>
			</ul>
		</li>
		<li class="dropdown">
			<a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">ladder<b class="caret"></b></a>
			<ul id="branches-dropdown" class="dropdown-menu">
				<li><a tabindex="-1" href="ladder">ladder</a></li>
				<li><a tabindex="-1" href="fence">fence</a></li>
				<li><a tabindex="-1" href="portaloo">portaloo</a></li>
			</ul>
		</li>
	</ul>
  
  <!-- item list -->
  <?php echo $this->result_list ?>
  <!-- /item list -->
  
  <p>
  <a href="http://www.bootply.com/render/129229">Demo</a> | <a href="http://bootply.com/129229">Source Code</a>
  </p>
  
  <hr> 
	
  <p>
  <a href="http://bootply.com" target="_ext" class="center-block btn btn-primary">More Bootstrap Snippets on Bootply</a>
  </p>
	
  <hr>      

</div>
<?php echo $this->map ?>
</div>
