<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
		<?php echo $this->headTitle('Rent Stuff');?>

		<?php
		
echo $this->headMeta()	->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1')
						->appendName('generator', 'Rent Stuff')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

		<!-- Le styles -->
		<?php
		
echo $this->headLink(array (
				'rel' => 'shortcut icon',
				'type' => 'image/x-icon',
				'href' => $this->basePath('img/favicon.ico')))
		->prependStylesheet($this->basePath('css/styles.css'))
		->prependStylesheet($this->basePath('css/bootstrap-slider.css'))
		->prependStylesheet($this->basePath('css/styles.css'))
		->prependStylesheet($this->basePath('css/typeaheadjs.css'))
		// ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
		->prependStylesheet($this->basePath('css/bootstrap.min.css'))?>

</head>
<body>
	<div class="navbar navbar-custom navbar-fixed-top">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">Rent Stuff Logo</a> <a
				class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-collapse"> <span class="icon-bar"></span> <span
				class="icon-bar"></span> <span class="icon-bar"></span>
			</a>
		</div>
		<div class="navbar-collapse collapse col-md-offset-2" style="overflow-y: visible">
			<form class="navbar-form">
				<div class="form-group" style="display: inline;">
					<div class="input-group">
						<input type="text" class="form-control typeahead twitter-typeahead" placeholder="Search" id="mainSearchBar"> <span
							class="input-group-addon"><span
							class="glyphicon glyphicon-search"></span> </span>
							
					</div>
				</div>
			</form>
		</div>
	</div>

	<div id="map-canvas"></div>
	<div class="container-fluid" id="main">
		<div class="row">
			<div class="col-xs-12 col-sm-8" id="left">
				<?php echo $this->content; ?>
				<p>&copy; 2014 - <?php echo date('Y') ?> by Rent Stuff. <?php echo $this->translate('All rights reserved.') ?></p>
			</div>
			<?php echo $this->map ?>
		</div>
	</div>
	<!-- /container -->
	 	<?php echo $this->inlineScript()?>

			<!-- Scripts -->
		<?php
		
echo $this->headScript()->prependFile($this->basePath('js/index.js'))
						->prependFile($this->basePath('js/googleMaps.js'))
						->prependFile($this->basePath('js/categories.js'))
						->prependFile($this->basePath('js/bootstrap-slider.js'))
						->prependFile($this->basePath('js/typeahead.bloodhound.js'))
						->prependFile($this->basePath('js/typeahead.js'))
						->prependFile($this->basePath('js/bootstrap.min.js'))
						->prependFile("//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js")
						->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'));
		?>
</body>
</html>
