<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="msapplication-TileColor" content="#168ccc">
<meta name="msapplication-TileImage" content="/img/mstile-144x144.png">
<meta name="msapplication-config" content="/img/browserconfig.xml">
<meta name="theme-color" content="#168ccc">
		<?php echo $this->headTitle('proxihire');?>

		<?php
		
echo $this->headMeta()	->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1')
						->appendName('generator', 'proxihire')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

		<!-- Le styles -->
		<?php
		
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath('img/favicon.ico')))
		->headLink(array('rel' => "apple-touch-icon", 	'sizes' => "57x57", 	'href' => $this->basePath('img/apple-touch-icon-57x57.png')))
		->headLink(array('rel' => "apple-touch-icon", 	'sizes' => "60x60", 	'href' => $this->basePath('img/apple-touch-icon-60x60.png')))
		->headLink(array('rel' => "apple-touch-icon", 	'sizes' => "72x72", 	'href' => $this->basePath('img/apple-touch-icon-72x72.png')))
		->headLink(array('rel' => "apple-touch-icon",	'sizes' => "76x76", 	'href' => $this->basePath('img/apple-touch-icon-76x76.png')))
		->headLink(array('rel' => "apple-touch-icon", 	'sizes' => "114x114", 	'href' => $this->basePath('img/apple-touch-icon-114x114.png')))
		->headLink(array('rel' => "apple-touch-icon", 	'sizes' => "120x120", 	'href' => $this->basePath('img/apple-touch-icon-120x120.png')))
		->headLink(array('rel' => "apple-touch-icon", 	'sizes' => "144x144", 	'href' => $this->basePath('img/apple-touch-icon-144x144.png')))
		->headLink(array('rel' => "apple-touch-icon", 	'sizes' => "152x152", 	'href' => $this->basePath('img/apple-touch-icon-152x152.png')))
		->headLink(array('rel' => "apple-touch-icon", 	'sizes' => "180x180", 	'href' => $this->basePath('img/apple-touch-icon-180x180.png')))
		->headLink(array('rel' => "icon", 				'sizes' => "32x32", 	'href' => $this->basePath('img/favicon-32x32.png'), 		'type' => 'image/png'))
		->headLink(array('rel' => "icon", 				'sizes' => "194x194", 	'href' => $this->basePath('img/favicon-194x194.png'), 		'type' => 'image/png'))
		->headLink(array('rel' => "icon", 				'sizes' => "96x96", 	'href' => $this->basePath('img/favicon-96x96.png'), 		'type' => 'image/png'))
		->headLink(array('rel' => "icon", 				'sizes' => "192x192", 	'href' => $this->basePath('img/android-chrome-192x192.png'),'type' => 'image/png'))
		->headLink(array('rel' => "icon", 				'sizes' => "16x16", 	'href' => $this->basePath('img/favicon-16x16.png'),			'type' => 'image/png'))
		->headLink(array('rel' => "manifest", 									'href' => $this->basePath('img/manifest.json')))
		->prependStylesheet($this->basePath('css/styles.css'))
		->prependStylesheet($this->basePath('css/bootstrap-slider.css'))
		->prependStylesheet($this->basePath('css/styles.css'))
		->prependStylesheet($this->basePath('css/typeaheadjs.css'))
		// ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
		->prependStylesheet($this->basePath('css/bootstrap.min.css'))

?>

</head>
<body>
	<div class="navbar navbar-custom navbar-fixed-top">
		<div class="navbar-header">
			<a class="navbar-brand" href="#"><img src="/img/proxihire_white_orange_133x40.png" style="margin-top: -10px;"/></a> <a
				class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-collapse"> <span class="icon-bar"></span> <span
				class="icon-bar"></span> <span class="icon-bar"></span>
			</a>
		</div>
		<div class="navbar-collapse collapse col-md-offset-2" style="overflow-y: visible">
			<form class="navbar-form">
				<div class="form-group" style="display: inline;">
					<div class="input-group">
						<input type="text" class="form-control typeahead twitter-typeahead" placeholder="Search" id="mainSearchBar"> <span
							class="input-group-addon"><span
							class="glyphicon glyphicon-search"></span> </span>
							
					</div>
				</div>
			</form>
		</div>
	</div>

	<div id="map-canvas"></div>
	<div class="container-fluid" id="main">
		<div class="row">
			<div class="col-xs-12 col-sm-8" id="left">
				<?php echo $this->content; ?>
				<p style="font-size:0.9em; text-align:center; margin-top: 15px;">&copy; 2014 - <?php echo date('Y') ?> by Proxihire. <?php echo $this->translate('All rights reserved.') ?></p>
			</div>
			<?php echo $this->map ?>
		</div>
	</div>
	<!-- /container -->
	 	<?php echo $this->inlineScript()?>

			<!-- Scripts -->
		<?php
		
echo $this->headScript()->prependFile($this->basePath('js/index.js'))
						->prependFile($this->basePath('js/googleMaps.js'))
						->prependFile($this->basePath('js/categories.js'))
						->prependFile($this->basePath('js/bootstrap-slider.js'))
						->prependFile($this->basePath('js/typeahead.bloodhound.js'))
						->prependFile($this->basePath('js/typeahead.js'))
						->prependFile($this->basePath('js/bootstrap.min.js'))
						->prependFile("//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js")
						->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'));
		?>
</body>
</html>
