<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<?php echo $this->headTitle('Rent Stuff');?>

		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1')
			->appendName('generator', 'Rent Stuff')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath( 'img/favicon.ico')))
			->prependStylesheet($this->basePath('css/styles.css'))
			//->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
			->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

			<!-- Scripts -->
		<?php echo $this->headScript()
			->prependFile($this->basePath('js/bootstrap.min.js'))
			->prependFile($this->basePath('js/categories.js'))
			->prependFile("//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js")
			->prependFile("http://maps.googleapis.com/maps/api/js?sensor=false&extension=.js&output=embed")
			->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
		; ?>

	</head>
	<body>
		<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?php echo $this->url('home') ?>">Rent Stuff Logo</a>
					<!--<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/rentstuff-logo.png') ?>" alt="Rent Stuff Logo"/></a>-->
				</div>
				<div class="collapse navbar-collapse col-md-offset-2">
					<form class="navbar-form">
						<div class="form-group" style="display:inline;">
							<div class="input-group">
								<input type="text" class="form-control" placeholder="Search">
								<span class="input-group-addon"><span class="glyphicon glyphicon-search"></span> </span>
							</div>
						</div>
					</form>
				</div><!--/.nav-collapse -->
			</div>
		</nav>
		<div class="container">
			<?php echo $this->content; ?>
			<hr>
				<footer>
					<p>&copy; 2014 - <?php echo date('Y') ?> by Rent Stuff. <?php echo $this->translate('All rights reserved.') ?></p>
				</footer>
			</div> <!-- /container -->
	 	<?php echo $this->inlineScript()->prependFile($this->basePath('js/scripts.js')) ?>
	</body>
</html>
