#!/bin/bash

mysql_user=$1
env_var=$2
echo "Attempting to connect to mysql as $mysql_user"
read -p "Password (blank for no password):" -s password
echo

password_option=""
if [ -n "$password" ]; then
	password_option=" -p$password"
fi

eval $env_var=\"\$password_option\"
